config/routes.rb
WorshipTogether::Application.routes.draw do
  root 'users#index'

  resources :users
  resources :churches, shallow: true do
    resources :services, shallow: true do
      resources :rides
    end
  end

  get 'login', to: 'logins#new', as: :login
  post 'login', to: 'logins#create', as: :logins
  delete 'logout', to: 'logins#destroy', as: :logout

end

app/models/church.rb
class Church < ActiveRecord::Base
  belongs_to :user, inverse_of: :church_managed
  has_many :services, inverse_of: :church
  has_many :users, inverse_of: :church

  accepts_nested_attributes_for :services
  
  validates :user, presence: true
  validates :name, presence: true
  validates :web_site, presence: true
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
  def new
	  @church = Church.new
	  @church.services.build
    unless current_user
      flash[:danger] = "You must be logged in to create a church"
      redirect_to login_path
    end
  end

  def create
    unless current_user
      flash[:danger] = "You must be logged in to create a church"
      redirect_to login_path
    end
	  @church = Church.new(church_params)
	  @church.user = current_user
    if(@church.user)
	    if (@church.save)
	      flash[:success] = "Church created"
	      redirect_to @church
      else #else if (@church.save)
	      flash.now[:danger] = "Unable to create church"
	      render 'new'
      end #end if (@church.save)
    else #else if @church.user exists
      flash[:danger] = "You must be logged in to create a church"
      redirect_to login_path
    end #end if @church.user
  end #end create
  
  def edit
    @church = Church.find(params[:id])
    if (current_user)
      if(@church)
        unless(@church.user == current_user)
          flash[:danger] = "You are not authorized to edit that church"
          redirect_to root_path #the user is not authorized to edit this church.
        end
      end
    else
      flash[:danger] = "You must be logged in to edit a church"
      redirect_to login_path
    end
    rescue
	    flash[:danger] = "Unable to find church"
      redirect_to root_path
  end
  
  def update
     @church = Church.find(params[:id])
      if @church.update(church_params)
        flash[:success] = "Church edited"
	      redirect_to @church
	    else
        flash.now[:danger] = "Unable to modify church"
        render 'edit'
	    end
  end
  
  def index
    @churches = Church.all
  end
  
  def show
    	@church = Church.find(params[:id])
    rescue
	  flash[:danger] = "Unable to find church"
    redirect_to root_path
  end
  
  def destroy
    @church = Church.find(params[:id])
    @user = @church.user
    if @user
      if(@church.destroy)
        flash[:success] = "Church deleted"
        redirect_to root_path
      else
        flash[:danger] = "Found not deleted"
        puts "church #{:id} was found but not deleted?"
        redirect_to root_path
      end
    else
      flash[:danger] = "You are not authorized to delete this church"
      redirect_to root_path
    end
    rescue
	  flash[:danger] = "Unable to find church"
    redirect_to root_path
  end

    private

    def church_params
	params.require(:church).permit(:name,
				       :web_site,
				       :description,
				       :picture,
               :users,
				       services_attributes: [ :start_time,
							      :finish_time,
							      :location,
                    :day_of_week,
                    :id] )
    end
end

app/views/churches/_church.html.erb
<li>
  <%= content_tag(:a, "#{church.name}", href: church_path(church)) %>
  <%= content_tag(:a, "official web site", href: church.web_site) %>
  <% if (logged_in?) %>
  <%= button_to "Attend this church", user_path(current_user, church_id: church.id), {method: :patch} %>
  <% end %>
  <%= link_to 'delete', church_path(church.id), method: :delete %>
</li>

app/views/churches/_fields.html.erb
<%= f.label :name, 'Name' %>
<%= f.text_field :name %>

<%= f.label :web_site %>
<%= f.text_field :web_site %>

<%= f.label :picture %>
<%= f.text_field :picture %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.fields_for :services do |builder| %>
    <%= builder.label :start_time %>
    <%= builder.text_field :start_time %>

    <%= builder.label :finish_time %>
    <%= builder.text_field :finish_time %>

    <%= builder.label :location %>
    <%= builder.text_field :location %>

    <%= builder.label :day_of_week %>
    <%= builder.text_field :day_of_week %>
<% end %>

app/views/churches/_service.html.erb
<li>
  <div class=<%="service#{service.id}"%> >
    <ul>
      <%=content_tag(:li, "Starts at: #{service.start_time}") %>
      <%=content_tag(:li, "Ends at: #{service.finish_time}")%>
      <%=content_tag(:li, "Location: #{service.location}") %>
    </ul>
  </div>
</li>

app/views/churches/edit.html.erb
<h1>Edit church profile</h1>
<%= form_for @church do |form| %>
    <%= render partial: 'fields', locals: { f: form } %>
<%= form.submit 'Update church profile' %>
<% end %>

app/views/churches/index.html.erb
<h1>List of churches</h1>

<p><%= pluralize(@churches.count, 'church') %></p>
<ol><%= render @churches %></ol>

app/views/churches/new.html.erb
<%= render 'shared/errors', object: @church %>

<%= form_for @church do |form| %>
    <%= render partial: 'fields', locals: { f: form } %>

    <%= form.submit 'Create new church' %>
<% end %>

app/views/churches/show.html.erb
<h1>Profile Page for <%= @church.name %></h1>

<p><%= content_tag(:a, "official web site", href: @church.web_site) %></p>
<p>Attendees</p>
<ol><%= render partial: 'users/user', collection: @church.users %></ol>
<p><%= "#{@church.name}\'s #{pluralize(@church.services.count, 'Service')}" %></p>
<ol><%= render partial: 'service', collection: @church.services %></ol>

<p></p>
  <% if (logged_in?) %>
  <%= button_to "Attend this church", user_path(current_user, church_id: @church.id), {method: :patch} %>
  <% end %>